p8105_hw2_mc5503.Rmd
================
mc5503
2023-10-01

``` r
library(tidyverse)
```

    ## ── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
    ## ✔ dplyr     1.1.3     ✔ readr     2.1.4
    ## ✔ forcats   1.0.0     ✔ stringr   1.5.0
    ## ✔ ggplot2   3.4.3     ✔ tibble    3.2.1
    ## ✔ lubridate 1.9.2     ✔ tidyr     1.3.0
    ## ✔ purrr     1.0.2     
    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## ✖ dplyr::filter() masks stats::filter()
    ## ✖ dplyr::lag()    masks stats::lag()
    ## ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

``` r
library(readxl)
```

# Problem 1

## tidy pols data

``` r
pols=read_csv("data/fivethirtyeight_datasets/pols-month.csv")|>
  separate(mon,into = c("year","month_num","day"),convert = TRUE)|>
  mutate(month=month.name[month_num])|>
  mutate(president=recode(prez_gop,"0"="dem","1"="gop","2"="gop"))|>
  select(year,month,everything(),-day,-prez_gop,-prez_dem,-month_num)
```

    ## Rows: 822 Columns: 9
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl  (8): prez_gop, gov_gop, sen_gop, rep_gop, prez_dem, gov_dem, sen_dem, r...
    ## date (1): mon
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

## tidy snp data

``` r
snp=read_csv("data/fivethirtyeight_datasets/snp.csv") |>
  separate(date, into = c("month", "day", "year"), convert = TRUE) |>
  mutate(year=ifelse(year>=50,1900+year,2000+year))|>
  arrange(year, month) |>
  mutate(month = month.name[month]) |>
  select(year, month, close) 
```

    ## Rows: 787 Columns: 2
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (1): date
    ## dbl (1): close
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

## tidy unemployment data

``` r
month_df = 
  tibble(
    month_num = 1:12,
    month_abbr = month.abb,
    month = month.name
  )

unemployment = 
  read_csv("data/fivethirtyeight_datasets/unemployment.csv") |>
  rename(year = Year) |>
  pivot_longer(
    Jan:Dec,
    names_to="month_abbr",
    values_to ="unemployment"
  )|>
  left_join(x=_,y=month_df)|>
  select(year,month,unemployment)
```

    ## Rows: 68 Columns: 13
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl (13): Year, Jan, Feb, Mar, Apr, May, Jun, Jul, Aug, Sep, Oct, Nov, Dec
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
    ## Joining with `by = join_by(month_abbr)`

## merge all the datasets

``` r
data_538=
  left_join(pols,snp)|>
  left_join(x=_,y=unemployment)
```

    ## Joining with `by = join_by(year, month)`
    ## Joining with `by = join_by(year, month)`

``` r
data_538
```

    ## # A tibble: 822 × 11
    ##     year month   gov_gop sen_gop rep_gop gov_dem sen_dem rep_dem president close
    ##    <dbl> <chr>     <dbl>   <dbl>   <dbl>   <dbl>   <dbl>   <dbl> <chr>     <dbl>
    ##  1  1947 January      23      51     253      23      45     198 dem          NA
    ##  2  1947 Februa…      23      51     253      23      45     198 dem          NA
    ##  3  1947 March        23      51     253      23      45     198 dem          NA
    ##  4  1947 April        23      51     253      23      45     198 dem          NA
    ##  5  1947 May          23      51     253      23      45     198 dem          NA
    ##  6  1947 June         23      51     253      23      45     198 dem          NA
    ##  7  1947 July         23      51     253      23      45     198 dem          NA
    ##  8  1947 August       23      51     253      23      45     198 dem          NA
    ##  9  1947 Septem…      23      51     253      23      45     198 dem          NA
    ## 10  1947 October      23      51     253      23      45     198 dem          NA
    ## # ℹ 812 more rows
    ## # ℹ 1 more variable: unemployment <dbl>

``` r
str(data_538)
```

    ## tibble [822 × 11] (S3: tbl_df/tbl/data.frame)
    ##  $ year        : num [1:822] 1947 1947 1947 1947 1947 ...
    ##  $ month       : chr [1:822] "January" "February" "March" "April" ...
    ##  $ gov_gop     : num [1:822] 23 23 23 23 23 23 23 23 23 23 ...
    ##  $ sen_gop     : num [1:822] 51 51 51 51 51 51 51 51 51 51 ...
    ##  $ rep_gop     : num [1:822] 253 253 253 253 253 253 253 253 253 253 ...
    ##  $ gov_dem     : num [1:822] 23 23 23 23 23 23 23 23 23 23 ...
    ##  $ sen_dem     : num [1:822] 45 45 45 45 45 45 45 45 45 45 ...
    ##  $ rep_dem     : num [1:822] 198 198 198 198 198 198 198 198 198 198 ...
    ##  $ president   : chr [1:822] "dem" "dem" "dem" "dem" ...
    ##  $ close       : num [1:822] NA NA NA NA NA NA NA NA NA NA ...
    ##  $ unemployment: num [1:822] NA NA NA NA NA NA NA NA NA NA ...

The `pols` dataset has 822 observations and 9 variables. It contains
information about the party affiliation distribution from years 1947 to
2015. The `snp` data has 787 observations and 3 variables, ranging from
years 1950 to 2015. The `unemployment` data has 816 observations and 3
variables ranging from years 1948 to 2015. When a democrat was
president, the average unemployment rate was 6.57. While for
republician, the average unemployment rate was 6.47.

# Problem 2

## import and clean the datasets

``` r
mr_tw=read_excel(
  "data/202207 Trash Wheel Collection Data.xlsx",
   sheet = "Mr. Trash Wheel",
   range= "A2:N549")|>
  janitor::clean_names()|>
  mutate(homes_powered=round(weight_tons*500/30))|>
  mutate(trash_wheel_name="Mr. Trash Wheel")|>
  mutate(year=as.numeric(year))
  
pro_tw=read_excel(
  "data/202207 Trash Wheel Collection Data.xlsx",
  sheet = "Professor Trash Wheel",
  range = "A2:M96")|>
  janitor::clean_names()|>
  mutate(homes_powered=round(weight_tons*500/30))|>
  mutate(trash_wheel_name="Professor Trash Wheel")

#cap_tw=read_excel(
#  "data/202207 Trash Wheel Collection Data.xlsx",
#  sheet = "Captain Trash Wheel",
#  range = "A2:K27")|>
#  janitor::clean_names()|>
#  mutate(homes_powered=round(weight_tons*500/30))|>
#  mutate(trash_wheel_name="Captain Trash Wheel")

gwy_tw=read_excel(
  "data/202207 Trash Wheel Collection Data.xlsx",
  sheet = "Gwynnda Trash Wheel",
  range = "A2:K108")|>
  janitor::clean_names()|>
  mutate(homes_powered=round(weight_tons*500/30))|>
  mutate(trash_wheel_name="Gwynnda Trash Wheel")
```

## combine all the datasets

``` r
tw_tidy=bind_rows(mr_tw,pro_tw,gwy_tw)|>
  select(date,trash_wheel_name,everything())

str(tw_tidy)
```

    ## tibble [747 × 16] (S3: tbl_df/tbl/data.frame)
    ##  $ date              : POSIXct[1:747], format: "2014-05-16" "2014-05-16" ...
    ##  $ trash_wheel_name  : chr [1:747] "Mr. Trash Wheel" "Mr. Trash Wheel" "Mr. Trash Wheel" "Mr. Trash Wheel" ...
    ##  $ dumpster          : num [1:747] 1 2 3 4 5 6 7 8 9 10 ...
    ##  $ month             : chr [1:747] "May" "May" "May" "May" ...
    ##  $ year              : num [1:747] 2014 2014 2014 2014 2014 ...
    ##  $ weight_tons       : num [1:747] 4.31 2.74 3.45 3.1 4.06 2.71 1.91 3.7 2.52 3.76 ...
    ##  $ volume_cubic_yards: num [1:747] 18 13 15 15 18 13 8 16 14 18 ...
    ##  $ plastic_bottles   : num [1:747] 1450 1120 2450 2380 980 1430 910 3580 2400 1340 ...
    ##  $ polystyrene       : num [1:747] 1820 1030 3100 2730 870 2140 1090 4310 2790 1730 ...
    ##  $ cigarette_butts   : num [1:747] 126000 91000 105000 100000 120000 90000 56000 112000 98000 130000 ...
    ##  $ glass_bottles     : num [1:747] 72 42 50 52 72 46 32 58 49 75 ...
    ##  $ grocery_bags      : num [1:747] 584 496 1080 896 368 ...
    ##  $ chip_bags         : num [1:747] 1162 874 2032 1971 753 ...
    ##  $ sports_balls      : num [1:747] 7.2 5.2 6 6 7.2 5.2 3.2 6.4 5.6 7.2 ...
    ##  $ homes_powered     : num [1:747] 72 46 58 52 68 45 32 62 42 63 ...
    ##  $ plastic_bags      : num [1:747] NA NA NA NA NA NA NA NA NA NA ...

The `mr_tw`, `pro_tw` and `gwy_tw` datasets tells about the weight of
trash, trash types and the quantity of each type.There were 547
dumpsters used by Mr. Trash Wheel ranged from 1900-01-20 to 2022-07-29.
The start date 1900-01-20 might be wrong and it might be 2014-05-16.
There are 94 dumpsters used by Professor Trash Wheel ranged from
2017-01-02 to 2022-07-18. There were 105 dumpsters used by Gwynnda Trash
Wheel ranged from 2021-07-03 to 2022-07-26.

The `tw_tidy` dataset contains information of all the dumspters used by
the three wheels.

Total weight of trash collected by Professor Trash Wheel is 1748.36
tons. The total number of cigarette butts collected by Gwynnda in July
of 2021 is 1.63^{4}.
